package com.hm.funds.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TCapitalAccountStatements implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.FUNDS_TRADE_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String fundsTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.ORDER_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.COM_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.COM_NAME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.COM_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String comType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.ACCOUNT_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.OPERATE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.FUNDSTRADE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String fundstradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.INCOME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.PAYOUT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private BigDecimal payout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.FREEZED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private BigDecimal freezedFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.RELEASED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private BigDecimal releasedFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.FUNDS_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String fundsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.FUNDS_AMOUNT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private BigDecimal fundsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.OTHER_BILL
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String otherBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.REMARK
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.CREATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.CREATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.UPDATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_account_statements.DELETED
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.ID
     *
     * @return the value of t_capital_account_statements.ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.ID
     *
     * @param id the value for t_capital_account_statements.ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.FUNDS_TRADE_NO
     *
     * @return the value of t_capital_account_statements.FUNDS_TRADE_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getFundsTradeNo() {
        return fundsTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.FUNDS_TRADE_NO
     *
     * @param fundsTradeNo the value for t_capital_account_statements.FUNDS_TRADE_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setFundsTradeNo(String fundsTradeNo) {
        this.fundsTradeNo = fundsTradeNo == null ? null : fundsTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.ORDER_NO
     *
     * @return the value of t_capital_account_statements.ORDER_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.ORDER_NO
     *
     * @param orderNo the value for t_capital_account_statements.ORDER_NO
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.COM_ID
     *
     * @return the value of t_capital_account_statements.COM_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.COM_ID
     *
     * @param comId the value for t_capital_account_statements.COM_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setComId(String comId) {
        this.comId = comId == null ? null : comId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.COM_NAME
     *
     * @return the value of t_capital_account_statements.COM_NAME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.COM_NAME
     *
     * @param comName the value for t_capital_account_statements.COM_NAME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.COM_TYPE
     *
     * @return the value of t_capital_account_statements.COM_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getComType() {
        return comType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.COM_TYPE
     *
     * @param comType the value for t_capital_account_statements.COM_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setComType(String comType) {
        this.comType = comType == null ? null : comType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.ACCOUNT_TYPE
     *
     * @return the value of t_capital_account_statements.ACCOUNT_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.ACCOUNT_TYPE
     *
     * @param accountType the value for t_capital_account_statements.ACCOUNT_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.OPERATE_TYPE
     *
     * @return the value of t_capital_account_statements.OPERATE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.OPERATE_TYPE
     *
     * @param operateType the value for t_capital_account_statements.OPERATE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.FUNDSTRADE_TYPE
     *
     * @return the value of t_capital_account_statements.FUNDSTRADE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getFundstradeType() {
        return fundstradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.FUNDSTRADE_TYPE
     *
     * @param fundstradeType the value for t_capital_account_statements.FUNDSTRADE_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setFundstradeType(String fundstradeType) {
        this.fundstradeType = fundstradeType == null ? null : fundstradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.INCOME
     *
     * @return the value of t_capital_account_statements.INCOME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.INCOME
     *
     * @param income the value for t_capital_account_statements.INCOME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.PAYOUT
     *
     * @return the value of t_capital_account_statements.PAYOUT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public BigDecimal getPayout() {
        return payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.PAYOUT
     *
     * @param payout the value for t_capital_account_statements.PAYOUT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setPayout(BigDecimal payout) {
        this.payout = payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.FREEZED_FUNDS
     *
     * @return the value of t_capital_account_statements.FREEZED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public BigDecimal getFreezedFunds() {
        return freezedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.FREEZED_FUNDS
     *
     * @param freezedFunds the value for t_capital_account_statements.FREEZED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setFreezedFunds(BigDecimal freezedFunds) {
        this.freezedFunds = freezedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.RELEASED_FUNDS
     *
     * @return the value of t_capital_account_statements.RELEASED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public BigDecimal getReleasedFunds() {
        return releasedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.RELEASED_FUNDS
     *
     * @param releasedFunds the value for t_capital_account_statements.RELEASED_FUNDS
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setReleasedFunds(BigDecimal releasedFunds) {
        this.releasedFunds = releasedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.FUNDS_TYPE
     *
     * @return the value of t_capital_account_statements.FUNDS_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getFundsType() {
        return fundsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.FUNDS_TYPE
     *
     * @param fundsType the value for t_capital_account_statements.FUNDS_TYPE
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setFundsType(String fundsType) {
        this.fundsType = fundsType == null ? null : fundsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.FUNDS_AMOUNT
     *
     * @return the value of t_capital_account_statements.FUNDS_AMOUNT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public BigDecimal getFundsAmount() {
        return fundsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.FUNDS_AMOUNT
     *
     * @param fundsAmount the value for t_capital_account_statements.FUNDS_AMOUNT
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setFundsAmount(BigDecimal fundsAmount) {
        this.fundsAmount = fundsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.OTHER_BILL
     *
     * @return the value of t_capital_account_statements.OTHER_BILL
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getOtherBill() {
        return otherBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.OTHER_BILL
     *
     * @param otherBill the value for t_capital_account_statements.OTHER_BILL
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setOtherBill(String otherBill) {
        this.otherBill = otherBill == null ? null : otherBill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.REMARK
     *
     * @return the value of t_capital_account_statements.REMARK
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.REMARK
     *
     * @param remark the value for t_capital_account_statements.REMARK
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.CREATE_USER_ID
     *
     * @return the value of t_capital_account_statements.CREATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.CREATE_USER_ID
     *
     * @param createUserId the value for t_capital_account_statements.CREATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.CREATE_TIME
     *
     * @return the value of t_capital_account_statements.CREATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.CREATE_TIME
     *
     * @param createTime the value for t_capital_account_statements.CREATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.UPDATE_USER_ID
     *
     * @return the value of t_capital_account_statements.UPDATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.UPDATE_USER_ID
     *
     * @param updateUserId the value for t_capital_account_statements.UPDATE_USER_ID
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.UPDATE_TIME
     *
     * @return the value of t_capital_account_statements.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.UPDATE_TIME
     *
     * @param updateTime the value for t_capital_account_statements.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_account_statements.DELETED
     *
     * @return the value of t_capital_account_statements.DELETED
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_account_statements.DELETED
     *
     * @param deleted the value for t_capital_account_statements.DELETED
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}