package com.hm.funds.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCapitalAccountExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public TCapitalAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andComIdIsNull() {
            addCriterion("COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(String value) {
            addCriterion("COM_ID =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(String value) {
            addCriterion("COM_ID <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(String value) {
            addCriterion("COM_ID >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(String value) {
            addCriterion("COM_ID >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(String value) {
            addCriterion("COM_ID <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(String value) {
            addCriterion("COM_ID <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLike(String value) {
            addCriterion("COM_ID like", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotLike(String value) {
            addCriterion("COM_ID not like", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<String> values) {
            addCriterion("COM_ID in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<String> values) {
            addCriterion("COM_ID not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(String value1, String value2) {
            addCriterion("COM_ID between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(String value1, String value2) {
            addCriterion("COM_ID not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComTypeIsNull() {
            addCriterion("COM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andComTypeIsNotNull() {
            addCriterion("COM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andComTypeEqualTo(String value) {
            addCriterion("COM_TYPE =", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotEqualTo(String value) {
            addCriterion("COM_TYPE <>", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeGreaterThan(String value) {
            addCriterion("COM_TYPE >", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeGreaterThanOrEqualTo(String value) {
            addCriterion("COM_TYPE >=", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLessThan(String value) {
            addCriterion("COM_TYPE <", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLessThanOrEqualTo(String value) {
            addCriterion("COM_TYPE <=", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLike(String value) {
            addCriterion("COM_TYPE like", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotLike(String value) {
            addCriterion("COM_TYPE not like", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeIn(List<String> values) {
            addCriterion("COM_TYPE in", values, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotIn(List<String> values) {
            addCriterion("COM_TYPE not in", values, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeBetween(String value1, String value2) {
            addCriterion("COM_TYPE between", value1, value2, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotBetween(String value1, String value2) {
            addCriterion("COM_TYPE not between", value1, value2, "comType");
            return (Criteria) this;
        }

        public Criteria andComNameIsNull() {
            addCriterion("COM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andComNameIsNotNull() {
            addCriterion("COM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andComNameEqualTo(String value) {
            addCriterion("COM_NAME =", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotEqualTo(String value) {
            addCriterion("COM_NAME <>", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThan(String value) {
            addCriterion("COM_NAME >", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThanOrEqualTo(String value) {
            addCriterion("COM_NAME >=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThan(String value) {
            addCriterion("COM_NAME <", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThanOrEqualTo(String value) {
            addCriterion("COM_NAME <=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLike(String value) {
            addCriterion("COM_NAME like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotLike(String value) {
            addCriterion("COM_NAME not like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameIn(List<String> values) {
            addCriterion("COM_NAME in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotIn(List<String> values) {
            addCriterion("COM_NAME not in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameBetween(String value1, String value2) {
            addCriterion("COM_NAME between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotBetween(String value1, String value2) {
            addCriterion("COM_NAME not between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andCashAccountIsNull() {
            addCriterion("CASH_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCashAccountIsNotNull() {
            addCriterion("CASH_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCashAccountEqualTo(BigDecimal value) {
            addCriterion("CASH_ACCOUNT =", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountNotEqualTo(BigDecimal value) {
            addCriterion("CASH_ACCOUNT <>", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountGreaterThan(BigDecimal value) {
            addCriterion("CASH_ACCOUNT >", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CASH_ACCOUNT >=", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountLessThan(BigDecimal value) {
            addCriterion("CASH_ACCOUNT <", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CASH_ACCOUNT <=", value, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountIn(List<BigDecimal> values) {
            addCriterion("CASH_ACCOUNT in", values, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountNotIn(List<BigDecimal> values) {
            addCriterion("CASH_ACCOUNT not in", values, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CASH_ACCOUNT between", value1, value2, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andCashAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CASH_ACCOUNT not between", value1, value2, "cashAccount");
            return (Criteria) this;
        }

        public Criteria andUsableCashIsNull() {
            addCriterion("USABLE_CASH is null");
            return (Criteria) this;
        }

        public Criteria andUsableCashIsNotNull() {
            addCriterion("USABLE_CASH is not null");
            return (Criteria) this;
        }

        public Criteria andUsableCashEqualTo(BigDecimal value) {
            addCriterion("USABLE_CASH =", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashNotEqualTo(BigDecimal value) {
            addCriterion("USABLE_CASH <>", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashGreaterThan(BigDecimal value) {
            addCriterion("USABLE_CASH >", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USABLE_CASH >=", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashLessThan(BigDecimal value) {
            addCriterion("USABLE_CASH <", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USABLE_CASH <=", value, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashIn(List<BigDecimal> values) {
            addCriterion("USABLE_CASH in", values, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashNotIn(List<BigDecimal> values) {
            addCriterion("USABLE_CASH not in", values, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USABLE_CASH between", value1, value2, "usableCash");
            return (Criteria) this;
        }

        public Criteria andUsableCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USABLE_CASH not between", value1, value2, "usableCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashIsNull() {
            addCriterion("ORDER_CASH is null");
            return (Criteria) this;
        }

        public Criteria andOrderCashIsNotNull() {
            addCriterion("ORDER_CASH is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCashEqualTo(BigDecimal value) {
            addCriterion("ORDER_CASH =", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_CASH <>", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashGreaterThan(BigDecimal value) {
            addCriterion("ORDER_CASH >", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_CASH >=", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashLessThan(BigDecimal value) {
            addCriterion("ORDER_CASH <", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_CASH <=", value, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashIn(List<BigDecimal> values) {
            addCriterion("ORDER_CASH in", values, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_CASH not in", values, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_CASH between", value1, value2, "orderCash");
            return (Criteria) this;
        }

        public Criteria andOrderCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_CASH not between", value1, value2, "orderCash");
            return (Criteria) this;
        }

        public Criteria andBillAccountIsNull() {
            addCriterion("BILL_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBillAccountIsNotNull() {
            addCriterion("BILL_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBillAccountEqualTo(BigDecimal value) {
            addCriterion("BILL_ACCOUNT =", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountNotEqualTo(BigDecimal value) {
            addCriterion("BILL_ACCOUNT <>", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountGreaterThan(BigDecimal value) {
            addCriterion("BILL_ACCOUNT >", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BILL_ACCOUNT >=", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountLessThan(BigDecimal value) {
            addCriterion("BILL_ACCOUNT <", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BILL_ACCOUNT <=", value, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountIn(List<BigDecimal> values) {
            addCriterion("BILL_ACCOUNT in", values, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountNotIn(List<BigDecimal> values) {
            addCriterion("BILL_ACCOUNT not in", values, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILL_ACCOUNT between", value1, value2, "billAccount");
            return (Criteria) this;
        }

        public Criteria andBillAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILL_ACCOUNT not between", value1, value2, "billAccount");
            return (Criteria) this;
        }

        public Criteria andUsableBillIsNull() {
            addCriterion("USABLE_BILL is null");
            return (Criteria) this;
        }

        public Criteria andUsableBillIsNotNull() {
            addCriterion("USABLE_BILL is not null");
            return (Criteria) this;
        }

        public Criteria andUsableBillEqualTo(BigDecimal value) {
            addCriterion("USABLE_BILL =", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillNotEqualTo(BigDecimal value) {
            addCriterion("USABLE_BILL <>", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillGreaterThan(BigDecimal value) {
            addCriterion("USABLE_BILL >", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USABLE_BILL >=", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillLessThan(BigDecimal value) {
            addCriterion("USABLE_BILL <", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USABLE_BILL <=", value, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillIn(List<BigDecimal> values) {
            addCriterion("USABLE_BILL in", values, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillNotIn(List<BigDecimal> values) {
            addCriterion("USABLE_BILL not in", values, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USABLE_BILL between", value1, value2, "usableBill");
            return (Criteria) this;
        }

        public Criteria andUsableBillNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USABLE_BILL not between", value1, value2, "usableBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillIsNull() {
            addCriterion("ORDER_BILL is null");
            return (Criteria) this;
        }

        public Criteria andOrderBillIsNotNull() {
            addCriterion("ORDER_BILL is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBillEqualTo(BigDecimal value) {
            addCriterion("ORDER_BILL =", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_BILL <>", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillGreaterThan(BigDecimal value) {
            addCriterion("ORDER_BILL >", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_BILL >=", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillLessThan(BigDecimal value) {
            addCriterion("ORDER_BILL <", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_BILL <=", value, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillIn(List<BigDecimal> values) {
            addCriterion("ORDER_BILL in", values, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_BILL not in", values, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_BILL between", value1, value2, "orderBill");
            return (Criteria) this;
        }

        public Criteria andOrderBillNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_BILL not between", value1, value2, "orderBill");
            return (Criteria) this;
        }

        public Criteria andRebateAccountIsNull() {
            addCriterion("REBATE_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRebateAccountIsNotNull() {
            addCriterion("REBATE_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRebateAccountEqualTo(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT =", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountNotEqualTo(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT <>", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountGreaterThan(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT >", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT >=", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountLessThan(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT <", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REBATE_ACCOUNT <=", value, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountIn(List<BigDecimal> values) {
            addCriterion("REBATE_ACCOUNT in", values, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountNotIn(List<BigDecimal> values) {
            addCriterion("REBATE_ACCOUNT not in", values, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REBATE_ACCOUNT between", value1, value2, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRebateAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REBATE_ACCOUNT not between", value1, value2, "rebateAccount");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 17 17:02:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}