package com.hm.funds.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCapitalManageApplicationExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public TCapitalManageApplicationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoIsNull() {
            addCriterion("FUNDSBACK_APPLY_NO is null");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoIsNotNull() {
            addCriterion("FUNDSBACK_APPLY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoEqualTo(String value) {
            addCriterion("FUNDSBACK_APPLY_NO =", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoNotEqualTo(String value) {
            addCriterion("FUNDSBACK_APPLY_NO <>", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoGreaterThan(String value) {
            addCriterion("FUNDSBACK_APPLY_NO >", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDSBACK_APPLY_NO >=", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoLessThan(String value) {
            addCriterion("FUNDSBACK_APPLY_NO <", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoLessThanOrEqualTo(String value) {
            addCriterion("FUNDSBACK_APPLY_NO <=", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoLike(String value) {
            addCriterion("FUNDSBACK_APPLY_NO like", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoNotLike(String value) {
            addCriterion("FUNDSBACK_APPLY_NO not like", value, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoIn(List<String> values) {
            addCriterion("FUNDSBACK_APPLY_NO in", values, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoNotIn(List<String> values) {
            addCriterion("FUNDSBACK_APPLY_NO not in", values, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoBetween(String value1, String value2) {
            addCriterion("FUNDSBACK_APPLY_NO between", value1, value2, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andFundsbackApplyNoNotBetween(String value1, String value2) {
            addCriterion("FUNDSBACK_APPLY_NO not between", value1, value2, "fundsbackApplyNo");
            return (Criteria) this;
        }

        public Criteria andSuplrNameIsNull() {
            addCriterion("SUPLR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSuplrNameIsNotNull() {
            addCriterion("SUPLR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSuplrNameEqualTo(String value) {
            addCriterion("SUPLR_NAME =", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameNotEqualTo(String value) {
            addCriterion("SUPLR_NAME <>", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameGreaterThan(String value) {
            addCriterion("SUPLR_NAME >", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameGreaterThanOrEqualTo(String value) {
            addCriterion("SUPLR_NAME >=", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameLessThan(String value) {
            addCriterion("SUPLR_NAME <", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameLessThanOrEqualTo(String value) {
            addCriterion("SUPLR_NAME <=", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameLike(String value) {
            addCriterion("SUPLR_NAME like", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameNotLike(String value) {
            addCriterion("SUPLR_NAME not like", value, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameIn(List<String> values) {
            addCriterion("SUPLR_NAME in", values, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameNotIn(List<String> values) {
            addCriterion("SUPLR_NAME not in", values, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameBetween(String value1, String value2) {
            addCriterion("SUPLR_NAME between", value1, value2, "suplrName");
            return (Criteria) this;
        }

        public Criteria andSuplrNameNotBetween(String value1, String value2) {
            addCriterion("SUPLR_NAME not between", value1, value2, "suplrName");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("CUST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("CUST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("CUST_NAME =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("CUST_NAME <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("CUST_NAME >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NAME >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("CUST_NAME <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_NAME <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("CUST_NAME like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("CUST_NAME not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("CUST_NAME in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("CUST_NAME not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("CUST_NAME between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("CUST_NAME not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeIsNull() {
            addCriterion("FUNDSBACK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeIsNotNull() {
            addCriterion("FUNDSBACK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeEqualTo(String value) {
            addCriterion("FUNDSBACK_TYPE =", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeNotEqualTo(String value) {
            addCriterion("FUNDSBACK_TYPE <>", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeGreaterThan(String value) {
            addCriterion("FUNDSBACK_TYPE >", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDSBACK_TYPE >=", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeLessThan(String value) {
            addCriterion("FUNDSBACK_TYPE <", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeLessThanOrEqualTo(String value) {
            addCriterion("FUNDSBACK_TYPE <=", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeLike(String value) {
            addCriterion("FUNDSBACK_TYPE like", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeNotLike(String value) {
            addCriterion("FUNDSBACK_TYPE not like", value, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeIn(List<String> values) {
            addCriterion("FUNDSBACK_TYPE in", values, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeNotIn(List<String> values) {
            addCriterion("FUNDSBACK_TYPE not in", values, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeBetween(String value1, String value2) {
            addCriterion("FUNDSBACK_TYPE between", value1, value2, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackTypeNotBetween(String value1, String value2) {
            addCriterion("FUNDSBACK_TYPE not between", value1, value2, "fundsbackType");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountIsNull() {
            addCriterion("FUNDSBACK_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountIsNotNull() {
            addCriterion("FUNDSBACK_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountEqualTo(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT =", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountNotEqualTo(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT <>", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountGreaterThan(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT >", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT >=", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountLessThan(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT <", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNDSBACK_AMOUNT <=", value, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountIn(List<BigDecimal> values) {
            addCriterion("FUNDSBACK_AMOUNT in", values, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountNotIn(List<BigDecimal> values) {
            addCriterion("FUNDSBACK_AMOUNT not in", values, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNDSBACK_AMOUNT between", value1, value2, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andFundsbackAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNDSBACK_AMOUNT not between", value1, value2, "fundsbackAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountIsNull() {
            addCriterion("APPLYFUNDS_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountIsNotNull() {
            addCriterion("APPLYFUNDS_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountEqualTo(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT =", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountNotEqualTo(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT <>", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountGreaterThan(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT >", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT >=", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountLessThan(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT <", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APPLYFUNDS_AMOUNT <=", value, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountIn(List<BigDecimal> values) {
            addCriterion("APPLYFUNDS_AMOUNT in", values, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountNotIn(List<BigDecimal> values) {
            addCriterion("APPLYFUNDS_AMOUNT not in", values, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPLYFUNDS_AMOUNT between", value1, value2, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyfundsAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPLYFUNDS_AMOUNT not between", value1, value2, "applyfundsAmount");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("APPLY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("APPLY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(String value) {
            addCriterion("APPLY_TIME =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(String value) {
            addCriterion("APPLY_TIME <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(String value) {
            addCriterion("APPLY_TIME >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_TIME >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(String value) {
            addCriterion("APPLY_TIME <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(String value) {
            addCriterion("APPLY_TIME <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLike(String value) {
            addCriterion("APPLY_TIME like", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotLike(String value) {
            addCriterion("APPLY_TIME not like", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<String> values) {
            addCriterion("APPLY_TIME in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<String> values) {
            addCriterion("APPLY_TIME not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(String value1, String value2) {
            addCriterion("APPLY_TIME between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(String value1, String value2) {
            addCriterion("APPLY_TIME not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkIsNull() {
            addCriterion("PAYBACK_MARK is null");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkIsNotNull() {
            addCriterion("PAYBACK_MARK is not null");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkEqualTo(String value) {
            addCriterion("PAYBACK_MARK =", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkNotEqualTo(String value) {
            addCriterion("PAYBACK_MARK <>", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkGreaterThan(String value) {
            addCriterion("PAYBACK_MARK >", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkGreaterThanOrEqualTo(String value) {
            addCriterion("PAYBACK_MARK >=", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkLessThan(String value) {
            addCriterion("PAYBACK_MARK <", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkLessThanOrEqualTo(String value) {
            addCriterion("PAYBACK_MARK <=", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkLike(String value) {
            addCriterion("PAYBACK_MARK like", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkNotLike(String value) {
            addCriterion("PAYBACK_MARK not like", value, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkIn(List<String> values) {
            addCriterion("PAYBACK_MARK in", values, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkNotIn(List<String> values) {
            addCriterion("PAYBACK_MARK not in", values, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkBetween(String value1, String value2) {
            addCriterion("PAYBACK_MARK between", value1, value2, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andPaybackMarkNotBetween(String value1, String value2) {
            addCriterion("PAYBACK_MARK not between", value1, value2, "paybackMark");
            return (Criteria) this;
        }

        public Criteria andToAccountIsNull() {
            addCriterion("TO_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andToAccountIsNotNull() {
            addCriterion("TO_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andToAccountEqualTo(String value) {
            addCriterion("TO_ACCOUNT =", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountNotEqualTo(String value) {
            addCriterion("TO_ACCOUNT <>", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountGreaterThan(String value) {
            addCriterion("TO_ACCOUNT >", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountGreaterThanOrEqualTo(String value) {
            addCriterion("TO_ACCOUNT >=", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountLessThan(String value) {
            addCriterion("TO_ACCOUNT <", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountLessThanOrEqualTo(String value) {
            addCriterion("TO_ACCOUNT <=", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountLike(String value) {
            addCriterion("TO_ACCOUNT like", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountNotLike(String value) {
            addCriterion("TO_ACCOUNT not like", value, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountIn(List<String> values) {
            addCriterion("TO_ACCOUNT in", values, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountNotIn(List<String> values) {
            addCriterion("TO_ACCOUNT not in", values, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountBetween(String value1, String value2) {
            addCriterion("TO_ACCOUNT between", value1, value2, "toAccount");
            return (Criteria) this;
        }

        public Criteria andToAccountNotBetween(String value1, String value2) {
            addCriterion("TO_ACCOUNT not between", value1, value2, "toAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNull() {
            addCriterion("BANK_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNotNull() {
            addCriterion("BANK_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountEqualTo(String value) {
            addCriterion("BANK_ACCOUNT =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotEqualTo(String value) {
            addCriterion("BANK_ACCOUNT <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThan(String value) {
            addCriterion("BANK_ACCOUNT >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ACCOUNT >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThan(String value) {
            addCriterion("BANK_ACCOUNT <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThanOrEqualTo(String value) {
            addCriterion("BANK_ACCOUNT <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLike(String value) {
            addCriterion("BANK_ACCOUNT like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotLike(String value) {
            addCriterion("BANK_ACCOUNT not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIn(List<String> values) {
            addCriterion("BANK_ACCOUNT in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotIn(List<String> values) {
            addCriterion("BANK_ACCOUNT not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountBetween(String value1, String value2) {
            addCriterion("BANK_ACCOUNT between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotBetween(String value1, String value2) {
            addCriterion("BANK_ACCOUNT not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeIsNull() {
            addCriterion("LATESTPAY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeIsNotNull() {
            addCriterion("LATESTPAY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeEqualTo(Date value) {
            addCriterion("LATESTPAY_TIME =", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeNotEqualTo(Date value) {
            addCriterion("LATESTPAY_TIME <>", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeGreaterThan(Date value) {
            addCriterion("LATESTPAY_TIME >", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LATESTPAY_TIME >=", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeLessThan(Date value) {
            addCriterion("LATESTPAY_TIME <", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeLessThanOrEqualTo(Date value) {
            addCriterion("LATESTPAY_TIME <=", value, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeIn(List<Date> values) {
            addCriterion("LATESTPAY_TIME in", values, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeNotIn(List<Date> values) {
            addCriterion("LATESTPAY_TIME not in", values, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeBetween(Date value1, Date value2) {
            addCriterion("LATESTPAY_TIME between", value1, value2, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andLatestpayTimeNotBetween(Date value1, Date value2) {
            addCriterion("LATESTPAY_TIME not between", value1, value2, "latestpayTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 17 17:07:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}