package com.hm.funds.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCapitalAccountStatementsExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public TCapitalAccountStatementsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoIsNull() {
            addCriterion("FUNDS_TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoIsNotNull() {
            addCriterion("FUNDS_TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoEqualTo(String value) {
            addCriterion("FUNDS_TRADE_NO =", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoNotEqualTo(String value) {
            addCriterion("FUNDS_TRADE_NO <>", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoGreaterThan(String value) {
            addCriterion("FUNDS_TRADE_NO >", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDS_TRADE_NO >=", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoLessThan(String value) {
            addCriterion("FUNDS_TRADE_NO <", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoLessThanOrEqualTo(String value) {
            addCriterion("FUNDS_TRADE_NO <=", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoLike(String value) {
            addCriterion("FUNDS_TRADE_NO like", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoNotLike(String value) {
            addCriterion("FUNDS_TRADE_NO not like", value, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoIn(List<String> values) {
            addCriterion("FUNDS_TRADE_NO in", values, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoNotIn(List<String> values) {
            addCriterion("FUNDS_TRADE_NO not in", values, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoBetween(String value1, String value2) {
            addCriterion("FUNDS_TRADE_NO between", value1, value2, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andFundsTradeNoNotBetween(String value1, String value2) {
            addCriterion("FUNDS_TRADE_NO not between", value1, value2, "fundsTradeNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andComIdIsNull() {
            addCriterion("COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(String value) {
            addCriterion("COM_ID =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(String value) {
            addCriterion("COM_ID <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(String value) {
            addCriterion("COM_ID >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(String value) {
            addCriterion("COM_ID >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(String value) {
            addCriterion("COM_ID <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(String value) {
            addCriterion("COM_ID <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLike(String value) {
            addCriterion("COM_ID like", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotLike(String value) {
            addCriterion("COM_ID not like", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<String> values) {
            addCriterion("COM_ID in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<String> values) {
            addCriterion("COM_ID not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(String value1, String value2) {
            addCriterion("COM_ID between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(String value1, String value2) {
            addCriterion("COM_ID not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComNameIsNull() {
            addCriterion("COM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andComNameIsNotNull() {
            addCriterion("COM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andComNameEqualTo(String value) {
            addCriterion("COM_NAME =", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotEqualTo(String value) {
            addCriterion("COM_NAME <>", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThan(String value) {
            addCriterion("COM_NAME >", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThanOrEqualTo(String value) {
            addCriterion("COM_NAME >=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThan(String value) {
            addCriterion("COM_NAME <", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThanOrEqualTo(String value) {
            addCriterion("COM_NAME <=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLike(String value) {
            addCriterion("COM_NAME like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotLike(String value) {
            addCriterion("COM_NAME not like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameIn(List<String> values) {
            addCriterion("COM_NAME in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotIn(List<String> values) {
            addCriterion("COM_NAME not in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameBetween(String value1, String value2) {
            addCriterion("COM_NAME between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotBetween(String value1, String value2) {
            addCriterion("COM_NAME not between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andComTypeIsNull() {
            addCriterion("COM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andComTypeIsNotNull() {
            addCriterion("COM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andComTypeEqualTo(String value) {
            addCriterion("COM_TYPE =", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotEqualTo(String value) {
            addCriterion("COM_TYPE <>", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeGreaterThan(String value) {
            addCriterion("COM_TYPE >", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeGreaterThanOrEqualTo(String value) {
            addCriterion("COM_TYPE >=", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLessThan(String value) {
            addCriterion("COM_TYPE <", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLessThanOrEqualTo(String value) {
            addCriterion("COM_TYPE <=", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeLike(String value) {
            addCriterion("COM_TYPE like", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotLike(String value) {
            addCriterion("COM_TYPE not like", value, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeIn(List<String> values) {
            addCriterion("COM_TYPE in", values, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotIn(List<String> values) {
            addCriterion("COM_TYPE not in", values, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeBetween(String value1, String value2) {
            addCriterion("COM_TYPE between", value1, value2, "comType");
            return (Criteria) this;
        }

        public Criteria andComTypeNotBetween(String value1, String value2) {
            addCriterion("COM_TYPE not between", value1, value2, "comType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNull() {
            addCriterion("ACCOUNT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNotNull() {
            addCriterion("ACCOUNT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE =", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE <>", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThan(String value) {
            addCriterion("ACCOUNT_TYPE >", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE >=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThan(String value) {
            addCriterion("ACCOUNT_TYPE <", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE <=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLike(String value) {
            addCriterion("ACCOUNT_TYPE like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotLike(String value) {
            addCriterion("ACCOUNT_TYPE not like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIn(List<String> values) {
            addCriterion("ACCOUNT_TYPE in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotIn(List<String> values) {
            addCriterion("ACCOUNT_TYPE not in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeBetween(String value1, String value2) {
            addCriterion("ACCOUNT_TYPE between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_TYPE not between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("OPERATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("OPERATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(String value) {
            addCriterion("OPERATE_TYPE =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(String value) {
            addCriterion("OPERATE_TYPE <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(String value) {
            addCriterion("OPERATE_TYPE >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_TYPE >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(String value) {
            addCriterion("OPERATE_TYPE <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_TYPE <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLike(String value) {
            addCriterion("OPERATE_TYPE like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotLike(String value) {
            addCriterion("OPERATE_TYPE not like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<String> values) {
            addCriterion("OPERATE_TYPE in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<String> values) {
            addCriterion("OPERATE_TYPE not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(String value1, String value2) {
            addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(String value1, String value2) {
            addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeIsNull() {
            addCriterion("FUNDSTRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeIsNotNull() {
            addCriterion("FUNDSTRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeEqualTo(String value) {
            addCriterion("FUNDSTRADE_TYPE =", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeNotEqualTo(String value) {
            addCriterion("FUNDSTRADE_TYPE <>", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeGreaterThan(String value) {
            addCriterion("FUNDSTRADE_TYPE >", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDSTRADE_TYPE >=", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeLessThan(String value) {
            addCriterion("FUNDSTRADE_TYPE <", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeLessThanOrEqualTo(String value) {
            addCriterion("FUNDSTRADE_TYPE <=", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeLike(String value) {
            addCriterion("FUNDSTRADE_TYPE like", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeNotLike(String value) {
            addCriterion("FUNDSTRADE_TYPE not like", value, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeIn(List<String> values) {
            addCriterion("FUNDSTRADE_TYPE in", values, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeNotIn(List<String> values) {
            addCriterion("FUNDSTRADE_TYPE not in", values, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeBetween(String value1, String value2) {
            addCriterion("FUNDSTRADE_TYPE between", value1, value2, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andFundstradeTypeNotBetween(String value1, String value2) {
            addCriterion("FUNDSTRADE_TYPE not between", value1, value2, "fundstradeType");
            return (Criteria) this;
        }

        public Criteria andIncomeIsNull() {
            addCriterion("INCOME is null");
            return (Criteria) this;
        }

        public Criteria andIncomeIsNotNull() {
            addCriterion("INCOME is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeEqualTo(BigDecimal value) {
            addCriterion("INCOME =", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotEqualTo(BigDecimal value) {
            addCriterion("INCOME <>", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeGreaterThan(BigDecimal value) {
            addCriterion("INCOME >", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INCOME >=", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeLessThan(BigDecimal value) {
            addCriterion("INCOME <", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INCOME <=", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeIn(List<BigDecimal> values) {
            addCriterion("INCOME in", values, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotIn(List<BigDecimal> values) {
            addCriterion("INCOME not in", values, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCOME between", value1, value2, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCOME not between", value1, value2, "income");
            return (Criteria) this;
        }

        public Criteria andPayoutIsNull() {
            addCriterion("PAYOUT is null");
            return (Criteria) this;
        }

        public Criteria andPayoutIsNotNull() {
            addCriterion("PAYOUT is not null");
            return (Criteria) this;
        }

        public Criteria andPayoutEqualTo(BigDecimal value) {
            addCriterion("PAYOUT =", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutNotEqualTo(BigDecimal value) {
            addCriterion("PAYOUT <>", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutGreaterThan(BigDecimal value) {
            addCriterion("PAYOUT >", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAYOUT >=", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutLessThan(BigDecimal value) {
            addCriterion("PAYOUT <", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAYOUT <=", value, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutIn(List<BigDecimal> values) {
            addCriterion("PAYOUT in", values, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutNotIn(List<BigDecimal> values) {
            addCriterion("PAYOUT not in", values, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAYOUT between", value1, value2, "payout");
            return (Criteria) this;
        }

        public Criteria andPayoutNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAYOUT not between", value1, value2, "payout");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsIsNull() {
            addCriterion("FREEZED_FUNDS is null");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsIsNotNull() {
            addCriterion("FREEZED_FUNDS is not null");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsEqualTo(BigDecimal value) {
            addCriterion("FREEZED_FUNDS =", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsNotEqualTo(BigDecimal value) {
            addCriterion("FREEZED_FUNDS <>", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsGreaterThan(BigDecimal value) {
            addCriterion("FREEZED_FUNDS >", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FREEZED_FUNDS >=", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsLessThan(BigDecimal value) {
            addCriterion("FREEZED_FUNDS <", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FREEZED_FUNDS <=", value, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsIn(List<BigDecimal> values) {
            addCriterion("FREEZED_FUNDS in", values, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsNotIn(List<BigDecimal> values) {
            addCriterion("FREEZED_FUNDS not in", values, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FREEZED_FUNDS between", value1, value2, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andFreezedFundsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FREEZED_FUNDS not between", value1, value2, "freezedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsIsNull() {
            addCriterion("RELEASED_FUNDS is null");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsIsNotNull() {
            addCriterion("RELEASED_FUNDS is not null");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsEqualTo(BigDecimal value) {
            addCriterion("RELEASED_FUNDS =", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsNotEqualTo(BigDecimal value) {
            addCriterion("RELEASED_FUNDS <>", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsGreaterThan(BigDecimal value) {
            addCriterion("RELEASED_FUNDS >", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELEASED_FUNDS >=", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsLessThan(BigDecimal value) {
            addCriterion("RELEASED_FUNDS <", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELEASED_FUNDS <=", value, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsIn(List<BigDecimal> values) {
            addCriterion("RELEASED_FUNDS in", values, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsNotIn(List<BigDecimal> values) {
            addCriterion("RELEASED_FUNDS not in", values, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELEASED_FUNDS between", value1, value2, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andReleasedFundsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELEASED_FUNDS not between", value1, value2, "releasedFunds");
            return (Criteria) this;
        }

        public Criteria andFundsTypeIsNull() {
            addCriterion("FUNDS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFundsTypeIsNotNull() {
            addCriterion("FUNDS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFundsTypeEqualTo(String value) {
            addCriterion("FUNDS_TYPE =", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeNotEqualTo(String value) {
            addCriterion("FUNDS_TYPE <>", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeGreaterThan(String value) {
            addCriterion("FUNDS_TYPE >", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDS_TYPE >=", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeLessThan(String value) {
            addCriterion("FUNDS_TYPE <", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeLessThanOrEqualTo(String value) {
            addCriterion("FUNDS_TYPE <=", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeLike(String value) {
            addCriterion("FUNDS_TYPE like", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeNotLike(String value) {
            addCriterion("FUNDS_TYPE not like", value, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeIn(List<String> values) {
            addCriterion("FUNDS_TYPE in", values, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeNotIn(List<String> values) {
            addCriterion("FUNDS_TYPE not in", values, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeBetween(String value1, String value2) {
            addCriterion("FUNDS_TYPE between", value1, value2, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsTypeNotBetween(String value1, String value2) {
            addCriterion("FUNDS_TYPE not between", value1, value2, "fundsType");
            return (Criteria) this;
        }

        public Criteria andFundsAmountIsNull() {
            addCriterion("FUNDS_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andFundsAmountIsNotNull() {
            addCriterion("FUNDS_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFundsAmountEqualTo(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT =", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountNotEqualTo(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT <>", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountGreaterThan(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT >", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT >=", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountLessThan(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT <", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNDS_AMOUNT <=", value, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountIn(List<BigDecimal> values) {
            addCriterion("FUNDS_AMOUNT in", values, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountNotIn(List<BigDecimal> values) {
            addCriterion("FUNDS_AMOUNT not in", values, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNDS_AMOUNT between", value1, value2, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andFundsAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNDS_AMOUNT not between", value1, value2, "fundsAmount");
            return (Criteria) this;
        }

        public Criteria andOtherBillIsNull() {
            addCriterion("OTHER_BILL is null");
            return (Criteria) this;
        }

        public Criteria andOtherBillIsNotNull() {
            addCriterion("OTHER_BILL is not null");
            return (Criteria) this;
        }

        public Criteria andOtherBillEqualTo(String value) {
            addCriterion("OTHER_BILL =", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillNotEqualTo(String value) {
            addCriterion("OTHER_BILL <>", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillGreaterThan(String value) {
            addCriterion("OTHER_BILL >", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_BILL >=", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillLessThan(String value) {
            addCriterion("OTHER_BILL <", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillLessThanOrEqualTo(String value) {
            addCriterion("OTHER_BILL <=", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillLike(String value) {
            addCriterion("OTHER_BILL like", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillNotLike(String value) {
            addCriterion("OTHER_BILL not like", value, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillIn(List<String> values) {
            addCriterion("OTHER_BILL in", values, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillNotIn(List<String> values) {
            addCriterion("OTHER_BILL not in", values, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillBetween(String value1, String value2) {
            addCriterion("OTHER_BILL between", value1, value2, "otherBill");
            return (Criteria) this;
        }

        public Criteria andOtherBillNotBetween(String value1, String value2) {
            addCriterion("OTHER_BILL not between", value1, value2, "otherBill");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 17 17:04:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_capital_account_statements
     *
     * @mbggenerated Fri Nov 17 17:04:13 CST 2017
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}