package com.hm.funds.pojo;

import java.io.Serializable;
import java.util.Date;

public class TReader implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.user_name
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.user_password
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.user_phone
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.create_time
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.create_user_id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.id
     *
     * @return the value of t_reader.id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.id
     *
     * @param id the value for t_reader.id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.user_name
     *
     * @return the value of t_reader.user_name
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.user_name
     *
     * @param userName the value for t_reader.user_name
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.user_password
     *
     * @return the value of t_reader.user_password
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.user_password
     *
     * @param userPassword the value for t_reader.user_password
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.user_phone
     *
     * @return the value of t_reader.user_phone
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.user_phone
     *
     * @param userPhone the value for t_reader.user_phone
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.create_time
     *
     * @return the value of t_reader.create_time
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.create_time
     *
     * @param createTime the value for t_reader.create_time
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.create_user_id
     *
     * @return the value of t_reader.create_user_id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.create_user_id
     *
     * @param createUserId the value for t_reader.create_user_id
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }
}