package com.hm.funds.mapper;

import com.hm.funds.pojo.TCapitalAccount;
import com.hm.funds.pojo.TCapitalAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCapitalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int countByExample(TCapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int deleteByExample(TCapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int insert(TCapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int insertSelective(TCapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    List<TCapitalAccount> selectByExample(TCapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    TCapitalAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCapitalAccount record, @Param("example") TCapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int updateByExample(@Param("record") TCapitalAccount record, @Param("example") TCapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int updateByPrimaryKeySelective(TCapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_account
     *
     * @mbggenerated Fri Nov 17 17:02:37 CST 2017
     */
    int updateByPrimaryKey(TCapitalAccount record);
}