package com.hm.funds.mapper;

import com.hm.funds.pojo.TCapitalManageApplication;
import com.hm.funds.pojo.TCapitalManageApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCapitalManageApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int countByExample(TCapitalManageApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int deleteByExample(TCapitalManageApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int insert(TCapitalManageApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int insertSelective(TCapitalManageApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    List<TCapitalManageApplication> selectByExample(TCapitalManageApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    TCapitalManageApplication selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCapitalManageApplication record, @Param("example") TCapitalManageApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int updateByExample(@Param("record") TCapitalManageApplication record, @Param("example") TCapitalManageApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int updateByPrimaryKeySelective(TCapitalManageApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_manage_application
     *
     * @mbggenerated Fri Nov 17 17:07:21 CST 2017
     */
    int updateByPrimaryKey(TCapitalManageApplication record);
}