package com.hm.funds.mapper;

import com.hm.funds.pojo.TReader;
import com.hm.funds.pojo.TReaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int countByExample(TReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int deleteByExample(TReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int insert(TReader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int insertSelective(TReader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    List<TReader> selectByExample(TReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    TReader selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") TReader record, @Param("example") TReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int updateByExample(@Param("record") TReader record, @Param("example") TReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int updateByPrimaryKeySelective(TReader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Sun Nov 26 09:12:27 CST 2017
     */
    int updateByPrimaryKey(TReader record);
}